
package InterfaceSegregation;

// EN ESTE EJEMPLO PODEMOS OBSERVAR QUE CONVIENE MÁS CREAR UNA INTERFAZ
// PARA CADA CARRERA EN LUGAR DE UNA INTERFAZ ESTUDIANTE DE PROPÓSITO GENERAL
// ASÍ NOS EVITAMOS EL INCONVENIENTE DE ATRIBUIRLE UN MÉTODO DE LOS QUE REQUEREN
// LOS ESTUDIANTES DE INGENIERÍA A LOS ESTUDIANTES DE MEDICINA Y VISCEVERSA

public interface EngineerStudents 
{
    public void AssignMathTest();
    public void AssignPhysicsText();
}